export type DemoRole = 'ADMIN' | 'EDITOR' | 'VIEWER'
export type DemoStatus = 'ACTIVO' | 'INACTIVO'

export interface DemoUser {
  id: number
  name: string
  email: string
  role: DemoRole
  status: DemoStatus
  createdAt: string
}

export const demoUsers: DemoUser[] = [
  {
    id: 1,
    name: 'Ana Torres',
    email: 'ana.torres@example.com',
    role: 'ADMIN',
    status: 'ACTIVO',
    createdAt: '2025-01-12',
  },
  {
    id: 2,
    name: 'Bruno Díaz',
    email: 'bruno.diaz@example.com',
    role: 'EDITOR',
    status: 'ACTIVO',
    createdAt: '2025-02-03',
  },
  {
    id: 3,
    name: 'Carla Núñez',
    email: 'carla.nunez@example.com',
    role: 'VIEWER',
    status: 'INACTIVO',
    createdAt: '2025-02-21',
  },
  {
    id: 4,
    name: 'Diego Salas',
    email: 'diego.salas@example.com',
    role: 'EDITOR',
    status: 'ACTIVO',
    createdAt: '2025-03-08',
  },
  {
    id: 5,
    name: 'Elena Ruiz',
    email: 'elena.ruiz@example.com',
    role: 'ADMIN',
    status: 'INACTIVO',
    createdAt: '2025-03-19',
  },
  {
    id: 6,
    name: 'Felipe Gómez',
    email: 'felipe.gomez@example.com',
    role: 'VIEWER',
    status: 'ACTIVO',
    createdAt: '2025-04-02',
  },
  {
    id: 7,
    name: 'Gabriela León',
    email: 'gabriela.leon@example.com',
    role: 'EDITOR',
    status: 'ACTIVO',
    createdAt: '2025-04-15',
  },
  {
    id: 8,
    name: 'Héctor Vega',
    email: 'hector.vega@example.com',
    role: 'VIEWER',
    status: 'INACTIVO',
    createdAt: '2025-05-01',
  },
  {
    id: 9,
    name: 'Irene Castro',
    email: 'irene.castro@example.com',
    role: 'ADMIN',
    status: 'ACTIVO',
    createdAt: '2025-05-20',
  },
  {
    id: 10,
    name: 'Javier Mora',
    email: 'javier.mora@example.com',
    role: 'EDITOR',
    status: 'ACTIVO',
    createdAt: '2025-06-04',
  },
  {
    id: 11,
    name: 'Karina Ríos',
    email: 'karina.rios@example.com',
    role: 'VIEWER',
    status: 'INACTIVO',
    createdAt: '2025-06-18',
  },
  {
    id: 12,
    name: 'Luis Paredes',
    email: 'luis.paredes@example.com',
    role: 'EDITOR',
    status: 'ACTIVO',
    createdAt: '2025-07-01',
  },
  {
    id: 13,
    name: 'Marta Fuentes',
    email: 'marta.fuentes@example.com',
    role: 'ADMIN',
    status: 'ACTIVO',
    createdAt: '2025-07-14',
  },
  {
    id: 14,
    name: 'Nicolás Rojas',
    email: 'nicolas.rojas@example.com',
    role: 'VIEWER',
    status: 'INACTIVO',
    createdAt: '2025-07-28',
  },
  {
    id: 15,
    name: 'Olga Méndez',
    email: 'olga.mendez@example.com',
    role: 'EDITOR',
    status: 'ACTIVO',
    createdAt: '2025-08-09',
  },
  {
    id: 16,
    name: 'Pablo Sáenz',
    email: 'pablo.saenz@example.com',
    role: 'VIEWER',
    status: 'ACTIVO',
    createdAt: '2025-08-22',
  },
  {
    id: 17,
    name: 'Queta Ibáñez',
    email: 'queta.ibanez@example.com',
    role: 'ADMIN',
    status: 'INACTIVO',
    createdAt: '2025-09-03',
  },
  {
    id: 18,
    name: 'Raúl Campos',
    email: 'raul.campos@example.com',
    role: 'EDITOR',
    status: 'ACTIVO',
    createdAt: '2025-09-17',
  },
  {
    id: 19,
    name: 'Sofía Herrera',
    email: 'sofia.herrera@example.com',
    role: 'VIEWER',
    status: 'ACTIVO',
    createdAt: '2025-10-01',
  },
  {
    id: 20,
    name: 'Tomás Aguirre',
    email: 'tomas.aguirre@example.com',
    role: 'EDITOR',
    status: 'INACTIVO',
    createdAt: '2025-10-15',
  },
  {
    id: 21,
    name: 'Úrsula Ponce',
    email: 'ursula.ponce@example.com',
    role: 'ADMIN',
    status: 'ACTIVO',
    createdAt: '2025-10-29',
  },
  {
    id: 22,
    name: 'Víctor Lozano',
    email: 'victor.lozano@example.com',
    role: 'VIEWER',
    status: 'ACTIVO',
    createdAt: '2025-11-10',
  },
  {
    id: 23,
    name: 'Wendy Castro',
    email: 'wendy.castro@example.com',
    role: 'EDITOR',
    status: 'INACTIVO',
    createdAt: '2025-11-24',
  },
  {
    id: 24,
    name: 'Ximena Ortiz',
    email: 'ximena.ortiz@example.com',
    role: 'ADMIN',
    status: 'ACTIVO',
    createdAt: '2025-12-05',
  },
]
